### PR TITLE
New message format RichEmbed with Pagination

### PR DESCRIPTION
**Pull request by asheliahut**

### CODE REVIEW

**Comment by asheliahut** [comment]
I don't have a ton of time to work on code clean up as it is necessary. I will have a very busy week at work. If this gets chosen or not hopefully this code will help others.

**Comment by asheliahut** [comment]
If you want to see images of the results feel free to look at: https://github.com/fixmyrights/discord-bot/issues/33

**Comment by finnbear** [comment]
The idea to divide updates into two categories, new bills and updated bills, and then display all the new bills in a normal list of bills is good!

**Comment by finnbear** [comment]
Pagination has now been implemented in native discord.js, in the reference implementation. Looking for other concepts to transfer from this PR.

**Comment by finnbear** [comment]
Closed, seeing as functionality has been re-implemented.

**Pull request closed without merging**
