### PR TITLE
Fix spelling of global key in `credentials.json`

### PR DESCRIPTION
**Pull request by TheDevMinerTV**

### CODE REVIEW

**Review by joaodforce — APPROVED** [review]
hehe that's embarrassing :P

**Comment by TheDevMinerTV** [comment]
@joaodforce Please don't delete my branch for development since it screws up my Git Flow configuration

**Comment by joaodforce** [comment]
Excuse me, only create a PULL REQUESTS once you want to get it merged. this repo is setup to automatically delete merged branches.

**Comment by TheDevMinerTV** [comment]
Ah okay

**Pull request merged**
